### ISSUE TITLE
website doesn't build

### ISSUE THREAD

**Issue by stineb** [padasch/tutorial_digital_soil_mapping#3]
See https://github.com/padasch/tutorial_digital_soil_mapping/actions/runs/6174822449/job/16760288494. 

We have the same problem on geco-bern/tutorial_digital_soil_mapping. (but we can only raise issues here)

**Comment by khufkens** [comment]
That's because the publish.yaml should be deleted. Only the quarto one should be used.

**Comment by khufkens** [comment]
fixed on geco-bern

**Comment by khufkens** [comment]
Also, doesn't seem to be the issue. You need to render offline. I'll disable the runner.


> [Page Deployment](https://github.com/padasch/tutorial_digital_soil_mapping#page-deployment)
>
> This repository is not rendered through GitHub runners because of the large tiff files required. To update the online deployment with new content, one has to create a fork (important: fork both branches, not just the main branch), get the data as described above, do desired changes, and run the bash command quarto publish gh-pages. See more information here: https://quarto.org/docs/publishing/github-pages.html#publish-command

**Comment by stineb** [comment]
The website is still not built but I don't understand why the problem now:
https://github.com/geco-bern/tutorial_digital_soil_mapping/actions/runs/6732945540/job/18300602396

The file `data-raw/soildata/berne_soil_sampling_locations.csv` is not found but is also not part of the repo. Why not? Should it be?

**Comment by khufkens** [comment]
I've no idea. Check the course on where to download the data. If not found
ask Pascal.

**Comment by stineb** [comment]
@padasch ?

**Comment by padasch** [comment]
Please read the README, it is all explained there.

Data: You have to add all data yourself locally. That is this folder you got from Madlene. The names of these folders and where to put them is explained in the README.

Deployment: Render package locally and add only the render files to the git commit. I think this should be everything in the `freeze` folder. But double-check the link I put in the README.

**Comment by padasch** [comment]
From what I can tell, some of your changes are published online, so any current breaks must have been on your side.

Example of renaming headings from [this commit](https://github.com/geco-bern/tutorial_digital_soil_mapping/commit/7245aa55ccd81a4aa1ec31a7b927b4e8f55fd5ba): 

my website: 
<img width="184" alt="image" src="https://github.com/padasch/tutorial_digital_soil_mapping/assets/80832353/fef7fa93-f677-49c1-9127-69183e91ef4b">



geco website:
<img width="233" alt="image" src="https://github.com/padasch/tutorial_digital_soil_mapping/assets/80832353/051faaa5-685f-4025-a1c3-4ceea41c664b">

**Comment by stineb** [comment]
Thanks for getting back (and reminding me), Pascal.
My problem is that I could render locally because the leaflet call `leaflet::addRasterImage()` gives an error.:
```r
Quitting from lines 198-250 [unnamed-chunk-7] (02-data_preparation.qmd)
Error in `leaflet::addRasterImage()`:
! inherits(x, "RasterLayer") is not TRUE
Backtrace:
  1. leaflet::addLegend(...)
 19. leaflet::addRasterImage(...)
 20. base::stopifnot(inherits(x, "RasterLayer"))
Execution halted
```

That's why I set the respective chunk to `eval = FALSE` and thus manage to render locally.

**Comment by padasch** [comment]
could have to do with spatial packages that no longer work since raster package was discontinued in Oct.
